@startuml

Value <|-- Card
Color <|-- Card

enum Color{
Green
Blue
Yellow
Purple
Brown
}

class Card {
private final Value valeur
private final Color color
public Card(Value value,Color color)
public Value getValue()
public Color getColor()
}

enum Value {
    ONE(1)
    TWO(2)
    THREE(3)
    FOUR(4)
    FIVE(5)
    SIX(6)
    SEVEN(7)
    EIGHT(8)
    NINE(9)
    private int valeur
    Value(int valeur)
    private int valeur()
}

@enduml